# Generated by Django 3.0.1 on 2020-01-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0003_auto_20200103_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftexchange',
            name='image',
            field=models.ImageField(default='assets\\img\\default\\santa-hat.svg', upload_to='media/img/%Y/%m/%d', verbose_name='Картинка для вида'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisator_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_exchange.GiftExchange'),
        ),
    ]
