# Generated by Django 3.0.1 on 2020-01-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0006_auto_20200103_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftexchange',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gift_exchange.UserProfile'),
        ),
    ]
