# Generated by Django 3.0.1 on 2020-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0007_giftexchange_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftexchange',
            options={'verbose_name': 'Обмен подарками', 'verbose_name_plural': 'Много обменов подарками'},
        ),
        migrations.AddField(
            model_name='giftexchange',
            name='the_draw_was',
            field=models.BooleanField(default=False, verbose_name='Была ли жеребьевка'),
        ),
    ]
