# Generated by Django 3.0.1 on 2020-01-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0008_auto_20200103_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftexchange',
            old_name='user',
            new_name='creator',
        ),
    ]
