# Generated by Django 3.0.1 on 2020-01-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0013_auto_20200105_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftexchange',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Url адрес сбора'),
        ),
    ]
