# Generated by Django 3.0.1 on 2020-01-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0014_auto_20200105_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftexchange',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Url адрес сбора'),
        ),
    ]
