# Generated by Django 3.0.1 on 2020-01-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0015_auto_20200105_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_exchange.GiftExchange'),
        ),
    ]
