# Generated by Django 3.0.1 on 2020-01-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0016_auto_20200105_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
