# Generated by Django 3.0.1 on 2020-01-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0023_auto_20200105_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftexchange',
            name='price_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='Ограничение по сумме'),
        ),
    ]
