# Generated by Django 3.0.1 on 2020-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0030_auto_20200106_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftexchange',
            name='price_start',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Минимальная стоимость подарка'),
        ),
        migrations.AlterField(
            model_name='giftexchange',
            name='price_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='Максимальная  стоимость подарка'),
        ),
    ]
