# Generated by Django 3.0.1 on 2020-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0032_auto_20200107_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftexchange',
            options={'verbose_name': 'Обмен подарками', 'verbose_name_plural': 'Обмены подарками'},
        ),
        migrations.AlterField(
            model_name='giftexchange',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Url адрес обмена'),
        ),
        migrations.AlterField(
            model_name='giftexchange',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название вашего обмена'),
        ),
    ]
