# Generated by Django 3.0.1 on 2020-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0033_auto_20200108_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(verbose_name='Напишите что бы вы хотели, а также укажите адрес куда ваш "Secret Santa" сможет доставить подарок.'),
        ),
    ]
