# Generated by Django 3.0.1 on 2020-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_exchange', '0041_auto_20200109_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftexchange',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='giftexchange',
            name='image',
            field=models.ImageField(blank=True, default='media/img/0000/00/00/gifts-5.jpg', null=True, upload_to='media/img/%Y/%m/%d', verbose_name='Картинка для вида'),
        ),
    ]
